# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beamstopCentering.ui'
#
# Created: Fri Dec 13 14:49:24 2013
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Beamstop(object):
    def setupUi(self, Beamstop):
        Beamstop.setObjectName("Beamstop")
        Beamstop.resize(929, 768)
        Beamstop.setSizeGripEnabled(False)
        self.verticalLayout = QtGui.QVBoxLayout(Beamstop)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setMargin(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBoxBeamstopY = QtGui.QGroupBox(Beamstop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxBeamstopY.sizePolicy().hasHeightForWidth())
        self.groupBoxBeamstopY.setSizePolicy(sizePolicy)
        self.groupBoxBeamstopY.setMinimumSize(QtCore.QSize(240, 75))
        self.groupBoxBeamstopY.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxBeamstopY.setObjectName("groupBoxBeamstopY")
        self.doubleSpinBoxBeamstopY = QtGui.QDoubleSpinBox(self.groupBoxBeamstopY)
        self.doubleSpinBoxBeamstopY.setGeometry(QtCore.QRect(120, 30, 91, 22))
        self.doubleSpinBoxBeamstopY.setDecimals(0)
        self.doubleSpinBoxBeamstopY.setMinimum(-10000.0)
        self.doubleSpinBoxBeamstopY.setMaximum(10000.0)
        self.doubleSpinBoxBeamstopY.setObjectName("doubleSpinBoxBeamstopY")
        self.labelBeamstopYposition = QtGui.QLabel(self.groupBoxBeamstopY)
        self.labelBeamstopYposition.setGeometry(QtCore.QRect(20, 25, 91, 26))
        self.labelBeamstopYposition.setFrameShape(QtGui.QFrame.Box)
        self.labelBeamstopYposition.setObjectName("labelBeamstopYposition")
        self.horizontalLayout.addWidget(self.groupBoxBeamstopY)
        self.groupBoxBeamstopZ = QtGui.QGroupBox(Beamstop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxBeamstopZ.sizePolicy().hasHeightForWidth())
        self.groupBoxBeamstopZ.setSizePolicy(sizePolicy)
        self.groupBoxBeamstopZ.setMinimumSize(QtCore.QSize(232, 80))
        self.groupBoxBeamstopZ.setObjectName("groupBoxBeamstopZ")
        self.doubleSpinBoxBeamstopZ = QtGui.QDoubleSpinBox(self.groupBoxBeamstopZ)
        self.doubleSpinBoxBeamstopZ.setGeometry(QtCore.QRect(130, 25, 91, 22))
        self.doubleSpinBoxBeamstopZ.setDecimals(0)
        self.doubleSpinBoxBeamstopZ.setMinimum(-10000.0)
        self.doubleSpinBoxBeamstopZ.setMaximum(10000.0)
        self.doubleSpinBoxBeamstopZ.setObjectName("doubleSpinBoxBeamstopZ")
        self.labelBeamstopZposition = QtGui.QLabel(self.groupBoxBeamstopZ)
        self.labelBeamstopZposition.setGeometry(QtCore.QRect(30, 25, 91, 21))
        self.labelBeamstopZposition.setFrameShape(QtGui.QFrame.Box)
        self.labelBeamstopZposition.setObjectName("labelBeamstopZposition")
        self.horizontalLayout.addWidget(self.groupBoxBeamstopZ)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_Flux = QtGui.QGroupBox(Beamstop)
        self.groupBox_Flux.setMinimumSize(QtCore.QSize(119, 80))
        self.groupBox_Flux.setObjectName("groupBox_Flux")
        self.doubleSpinBoxCurrentDiodeFlux = QtGui.QDoubleSpinBox(self.groupBox_Flux)
        self.doubleSpinBoxCurrentDiodeFlux.setGeometry(QtCore.QRect(15, 25, 81, 21))
        self.doubleSpinBoxCurrentDiodeFlux.setMinimum(-999999.0)
        self.doubleSpinBoxCurrentDiodeFlux.setMaximum(999999.0)
        self.doubleSpinBoxCurrentDiodeFlux.setObjectName("doubleSpinBoxCurrentDiodeFlux")
        self.horizontalLayout_3.addWidget(self.groupBox_Flux)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox = QtGui.QGroupBox(Beamstop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(248, 75))
        self.groupBox.setObjectName("groupBox")
        self.pushButtonSave = QtGui.QPushButton(self.groupBox)
        self.pushButtonSave.setGeometry(QtCore.QRect(170, 40, 66, 25))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonStopAutocenter = QtGui.QPushButton(self.groupBox)
        self.pushButtonStopAutocenter.setEnabled(False)
        self.pushButtonStopAutocenter.setGeometry(QtCore.QRect(10, 40, 151, 25))
        self.pushButtonStopAutocenter.setObjectName("pushButtonStopAutocenter")
        self.pushButtonAutocenterBeamstop = QtGui.QPushButton(self.groupBox)
        self.pushButtonAutocenterBeamstop.setGeometry(QtCore.QRect(10, 10, 151, 25))
        self.pushButtonAutocenterBeamstop.setObjectName("pushButtonAutocenterBeamstop")
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBarScan = QtGui.QProgressBar(Beamstop)
        self.progressBarScan.setProperty("value", 0)
        self.progressBarScan.setObjectName("progressBarScan")
        self.verticalLayout.addWidget(self.progressBarScan)
        self.horizontalLayout_2Dplot = QtGui.QHBoxLayout()
        self.horizontalLayout_2Dplot.setObjectName("horizontalLayout_2Dplot")
        self.verticalLayout.addLayout(self.horizontalLayout_2Dplot)
        self.textEditBeamstopCenterLog = QtGui.QTextEdit(Beamstop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditBeamstopCenterLog.sizePolicy().hasHeightForWidth())
        self.textEditBeamstopCenterLog.setSizePolicy(sizePolicy)
        self.textEditBeamstopCenterLog.setMinimumSize(QtCore.QSize(0, 130))
        self.textEditBeamstopCenterLog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEditBeamstopCenterLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditBeamstopCenterLog.setAutoFormatting(QtGui.QTextEdit.AutoNone)
        self.textEditBeamstopCenterLog.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.textEditBeamstopCenterLog.setReadOnly(True)
        self.textEditBeamstopCenterLog.setTabStopWidth(100)
        self.textEditBeamstopCenterLog.setAcceptRichText(False)
        self.textEditBeamstopCenterLog.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textEditBeamstopCenterLog.setObjectName("textEditBeamstopCenterLog")
        self.verticalLayout.addWidget(self.textEditBeamstopCenterLog)

        self.retranslateUi(Beamstop)
        QtCore.QMetaObject.connectSlotsByName(Beamstop)

    def retranslateUi(self, Beamstop):
        Beamstop.setWindowTitle(QtGui.QApplication.translate("Beamstop", "Beamstop centering tool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxBeamstopY.setTitle(QtGui.QApplication.translate("Beamstop", "Horizontal position", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxBeamstopY.setSuffix(QtGui.QApplication.translate("Beamstop", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBeamstopYposition.setText(QtGui.QApplication.translate("Beamstop", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxBeamstopZ.setTitle(QtGui.QApplication.translate("Beamstop", "Vertical position", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxBeamstopZ.setSuffix(QtGui.QApplication.translate("Beamstop", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBeamstopZposition.setText(QtGui.QApplication.translate("Beamstop", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Flux.setTitle(QtGui.QApplication.translate("Beamstop", "Diode flux", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxCurrentDiodeFlux.setSuffix(QtGui.QApplication.translate("Beamstop", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("Beamstop", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStopAutocenter.setText(QtGui.QApplication.translate("Beamstop", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAutocenterBeamstop.setText(QtGui.QApplication.translate("Beamstop", "Autocenter beamstop", None, QtGui.QApplication.UnicodeUTF8))

