#!/bin/sh

# When you've edited the relevant parameters, delete this comment and the following two lines
echo "You need to edit this script first, to set the space group and cell parameters."
#exit 1
#echo file $1
INPUT=$1
#INPUT=/gpfs/cfel/cxi/scratch/data/2020/EXFEL-2019-Schmidt-Mar-p002450/scratch/galchenm/data_processing/cheetah_processing/June_indexing_own_mask/1196_p8_snr5/j_stream/try_phenix/all_runs_sph.hkl 
OUTFILE=`echo $INPUT | sed -e 's/\.hkl$/.mtz/'`
echo $OUTFILE

echo " Input: $1"
echo "Output: $OUTFILE"
if [ -e $OUTFILE ]; then
	echo "   The output file already exists:"
	echo "   " $OUTFILE
	echo "   To confirm that you want to continue, which will DESTROY the"
	echo "   current contents of this file, type 'y' and press enter."
	read conf
	if [ $conf != y ]; then
		echo "Not confirmed."
		exit 1
	else
		echo "Proceeding"
	fi
fi

sed -n '/End\ of\ reflections/q;p' $INPUT > create-mtz.temp.hkl

echo "Running 'f2mtz'..."
f2mtz HKLIN create-mtz.temp.hkl HKLOUT $OUTFILE > out.html << EOF
TITLE Reflections from CrystFEL
NAME PROJECT wibble CRYSTAL wibble DATASET wibble
CELL 52.02 63.68 66.81 90  90 90
SYMM P222
SKIP 3
LABOUT H K L IMEAN SIGIMEAN
CTYPE  H H H J     Q
FORMAT '(3(F4.0,1X),F10.2,10X,F10.2)'
EOF

if [ $? -ne 0 ]; then echo "Failed."; exit; fi

rm -f create-mtz.temp.hkl
echo "Done."
